### PR TITLE
Remove /laboratory/ prefix from docker image

### PR DESCRIPTION
**Pull request by jacekn**
The image is not in use yet and we'd like to simplify architecture a little bit

### CODE REVIEW

**Comment by vcarl** [comment]
I think you'll have to remove [this line](https://github.com/stellar/laboratory/blob/master/webpack.config.base.js#L11) for this to work. Build right now emits assets that assumes they're hosted from `laboratory/`

**Comment by jacekn** [comment]
> I think you'll have to remove [this line](https://github.com/stellar/laboratory/blob/master/webpack.config.base.js#L11) for this to work. Build right now emits assets that assumes they're hosted from `laboratory/`

@vcarl thanks, this is a very good point. I think we need a transition period so I added rewrite rule to the dockerfile to support /laboratory/ prefix. This way we don't change anything for existing deployment while allowing dockerized one to strip the prefix.
I added @brahman81 to reviewers to get review for ops perspective as well.

**Comment by brahman81** [comment]
`https://laboratory.stellar.org/laboratory` 404's whilst `https://laboratory.stellar.org/laboratory/` doesn't. (trailing `/`)

**Comment by jacekn** [comment]
> `https://laboratory.stellar.org/laboratory` 404's whilst `https://laboratory.stellar.org/laboratory/` doesn't. (trailing `/`)

@brahman81 that's fixed now

**Pull request merged**
