### PR TITLE
Collapsible Pretty JSON

### PR DESCRIPTION
**Pull request by quietbits**
- Collapsible Pretty JSON (enabled by default)
- Underline links

image

image

### CODE REVIEW

**Comment by janewang** [comment]
This looks great!

**Review by jeesunikim — APPROVED** [review]
love it

**Comment by janewang** [comment]
@quietbits Will you be adding line numbers?

**Comment by quietbits** [comment]
> @quietbits Will you be adding line numbers?

@janewang Unfortunately, no. This type of component can't support line numbers. JSON objects are rendered in blocks, so it makes it very difficult to get individual lines to add the numbers. For that, we would need to use an IDE library (with limited UI customization).

Libraries that support only pretty printing JSON don't have numbers either ([react-json-view](https://uiwjs.github.io/react-json-view/), [json-edit-react](https://carlosnz.github.io/json-edit-react/), [react18-json-view](https://jv.yysuni.com/)).

**Pull request merged**
