### PR TITLE
add /trade_aggregations endpoint

### PR DESCRIPTION
**Pull request by robertDurst**
I was unsure what to title the label for this endpoint, so I just called it "Trade Aggregations"

screen shot 2018-01-30 at 5 47 00 pm

### CODE REVIEW

**Comment by bartekn** [comment]
Looks good! Please [sign the Contributor License Agreement](https://docs.google.com/forms/d/1g7EF6PERciwn7zfmfke5Sir2n10yddGGSXyZsq98tVY/viewform?usp=send_form) and I'll merge it.

We have very similar issue here: https://github.com/stellar/laboratory/issues/184 if you're willing to help more.

**Comment by robertDurst** [comment]
Hey @bartekn signed the Contributor License Agreement, but was curious if this is necessary since I am working for SDF :)

I'll definitely check out #184 later today!

**Comment by bartekn** [comment]
@robertDurst really sorry, still not familiar with your surname. Also, one of disadvantages working remotely...

Merging! 😄

**Comment by robertDurst** [comment]
@bartekn no worries! I got ahead on customer service stuff and this is my first PR here!

**Pull request merged**
