### PR TITLE
bump trezor-connect to 8.2.4-extended.

### PR DESCRIPTION
**Pull request by overcat**
We need to upgrade to the latest version to ensure that the signature is correct, please check this issue(https://github.com/trezor/connect/issues/970) for details.

I'm still waiting for an update from the Trezor team, I will mark this PR as ready later.

### CODE REVIEW

**Review by quietbits — APPROVED** [review]
Thanks @overcat ! :raised_hands: :rocket: I can confirm that the update worked for me locally with the latest Trezor One firmware.

**Comment by overcat** [comment]
Hi, @quietbits, please let me know once you have it in production, thank you.

**Comment by quietbits** [comment]
@overcat updates were pushed to production. :rocket:

**Comment by overcat** [comment]
> @overcat updates were pushed to production. 🚀

Thank you! @quietbits

**Pull request merged**
