### PR TITLE
Add `include_failed` to transaction endpoints

### LINKED ISSUE #373: Add include_failed option to query builder
An option for `include_failed`, to include failed transactions should be added to endpoint explorer for operations and transactions

### PR DESCRIPTION
**Pull request by vcarl**
Resolves #373

### CODE REVIEW

**Comment by bartekn** [comment]
You can pass this parameter to `/operations` and `/payments` (including per ledger, per account) too.

**Comment by vcarl** [comment]
Ah good to know! Thanks

**Comment by vcarl** [comment]
@bartekn Happy to add links, but from a quick scan of the ledger docs page, I didn't see failed transactions at all. Is there a specific doc you have in mind?

**Comment by bartekn** [comment]
You are correct, we should probably improve docs about ledger and for now just add a short info note like: "Stellar Ledger stores information about failed transactions too." or similar.

**Comment by vcarl** [comment]
I don't see any existing code for for docs next to endpoint explorer inputs, so in the interest of keeping this focused I'm going to merge as-is.

**Pull request merged**
